#!/bin/bash

OUTPUT_IMAGE="/tmp/i3lock.png"

#Take screenshot:
scrot $OUTPUT_IMAGE

#Execute ImageMagick:
PARAMS="$OUTPUT_IMAGE -scale 10% -scale 1000% $OUTPUT_IMAGE"
eval convert $PARAMS

#Lock the screen:
i3lock -i $OUTPUT_IMAGE -t -e

#Remove the generated image:
rm $OUTPUT_IMAGE
