#!/bin/bash
# All options are here: http://www.imagemagick.org/Usage/blur/#blur_args
BLURTYPE="0x5"
#BLURTYPE="0x2"
#BLURTYPE="5x3"
#BLURTYPE="2x8"
#BLURTYPE="2x3"

OUTPUT_IMAGE="/tmp/i3lock.png"

#Take screenshot:
scrot $OUTPUT_IMAGE

#Execute ImageMagick:
PARAMS="'$OUTPUT_IMAGE' '-level' '0%,100%,0.6' '-blur' '$BLURTYPE' '$OUTPUT_IMAGE'"
eval convert $PARAMS

#Lock the screen:
i3lock -i $OUTPUT_IMAGE -t -e

#Remove the generated image:
rm $OUTPUT_IMAGE
